name: qvault
description: A Flutter-based app locker with PIN authentication.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Core app dependencies
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.8
  flutter_local_notifications: ^17.2.2
  crypto: ^3.0.3
  sqflite: ^2.3.3
  path: ^1.9.0
  logger: ^2.0.1
  path_provider: ^2.0.11
  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
